Update patch set 5
Patch Set 5:

Looks like this commit breaks building on gcc 4.8. I'm not sure if this is a compiler version you're aiming to support, but just thought I'd mention it.

    src/client/linux/minidump_writer/linux_core_dumper.cc: In member function 'virtual bool google_breakpad::LinuxCoreDumper::EnumerateThreads()':
    src/client/linux/minidump_writer/linux_core_dumper.cc:248:66: error: narrowing conversion of '(__pid_t)info->siginfo::_sifields.siginfo::<anonymous union>::_kill.siginfo::<anonymous union>::<anonymous struct>::si_pid' from '__pid_t {aka int}' to 'long unsigned int' inside { } [-Werror=narrowing]
                 set_crash_exception_info({info->si_pid, info->si_uid});
                                                                      ^
    src/client/linux/minidump_writer/linux_core_dumper.cc:248:66: error: narrowing conversion of 'info->siginfo::_sifields.siginfo::<anonymous union>::_kill.siginfo::<anonymous union>::<anonymous struct>::si_pid' from 'const __pid_t {aka const int}' to 'long unsigned int' inside { } [-Werror=narrowing]
    src/client/linux/minidump_writer/linux_core_dumper.cc:251:45: error: 'const siginfo_t' has no member named 'si_syscall'
                 set_crash_exception_info({info->si_syscall, info->si_arch});
                                                 ^
    src/client/linux/minidump_writer/linux_core_dumper.cc:251:63: error: 'const siginfo_t' has no member named 'si_arch'
                 set_crash_exception_info({info->si_syscall, info->si_arch});
                                                                   ^
    src/client/linux/minidump_writer/linux_core_dumper.cc:251:71: error: no matching function for call to 'google_breakpad::LinuxCoreDumper::set_crash_exception_info(<brace-enclosed initializer list>)'
                 set_crash_exception_info({info->si_syscall, info->si_arch});
                                                                           ^
    src/client/linux/minidump_writer/linux_core_dumper.cc:251:71: note: candidate is:
    In file included from ./src/client/linux/minidump_writer/linux_core_dumper.h:37:0,
                     from src/client/linux/minidump_writer/linux_core_dumper.cc:33:
    ./src/client/linux/minidump_writer/linux_dumper.h:190:8: note: void google_breakpad::LinuxDumper::set_crash_exception_info(const std::vector<long unsigned int>&)
       void set_crash_exception_info(const std::vector<uint64_t>& exception_info) {
            ^
    ./src/client/linux/minidump_writer/linux_dumper.h:190:8: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const std::vector<long unsigned int>&'

Patch-set: 5
CC: Gerrit User 1335082 <1335082@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>