Revert "Allow symupload to take .sym files as input."
This reverts commit d9e7473f6a2f572b6d78735199fee6f4f565554d.

Reason for revert: Broken on Windows systems and is blocking uprev in
Chromium as a result.  https://crrev.com/c/7392920 as an example.

src/tools/windows/symupload/symupload.cc(162,10): error: use of undeclared identifier 'GetModuleInfoFromSymFile'
  162 |   return GetModuleInfoFromSymFile(temp_filename, pdb_info);
src/tools/windows/symupload/symupload.cc(191,56): error: no member named 'UTF8ToWide' in 'google_breakpad::WindowsStringUtils'
  191 |   pdb_info->cpu = google_breakpad::WindowsStringUtils::UTF8ToWide(cpu_str);

Original change's description:
> Allow symupload to take .sym files as input.
>
> This change enables symupload to directly process Breakpad symbol files (.sym). When a .sym file is provided, the module information (OS, CPU, debug ID, and filename) is extracted from the first line of the .sym file. The temporary file cleanup is also adjusted to only remove the generated .sym file when the input was not already a .sym file.
>
> Bug: 459506875
> Change-Id: I54c796733654aebf30528ac6eda6f0ca5b85378a
> Reviewed-on: https://chromium-review.googlesource.com/c/breakpad/breakpad/+/7231157
> Reviewed-by: Mike Frysinger <vapier@chromium.org>
> Reviewed-by: Joshua Peraza <jperaza@chromium.org>

Bug: 459506875
Change-Id: I10b9adb3b0e9ec7c3b760da83025a586e64e9b8d
Reviewed-on: https://chromium-review.googlesource.com/c/breakpad/breakpad/+/7474647
Reviewed-by: Joshua Peraza <jperaza@chromium.org>